.TH garden.tau.Outbox 1 "January 2024" outbox

.SH NAME
garden.tau.Outbox \- The D-Bus interface of
.MR outboxd 1

.SH THE OUTBOX OBJECT
The service exposes the following interface on the outbox object on the bus:

.sp
.if n \{\
.RS 4
.\}
.nf
node /garden/tau/Outbox {
    interface garden.tau.Outbox1 {
        methods:
          Queue(in h mail);
    };

    interface org.freedesktop.DBus.Peer { ... };
    interface org.freedesktop.DBus.Introspectable { ... };
    interface org.freedesktop.DBus.Properties { ... };
};
.fi
.if n \{\
.RE
.\}

.IP \fBMethods\fP
.B Queue()
adds a new message to the queue. The message data is provided by passing a file descriptor.
The passed file descriptor has to be readable.
