.TH OUTBOXD 1 "January 2024" outbox

.SH NAME
outboxd \- Mail queue daemon for msmtp

.SH SYNOPSIS
.SY outboxd
.RI [ option\~ .\|.\|.]
.YS

.SH DESCRIPTION
\fBoutboxd\fP is a daemon that provides a mail queue for msmtp. Messages are accepted via the
.MR garden.tau.Outbox 1
interface.

To send messages, \fBoutboxd\fP calls \fImsmtp\fP as follows:
.IP
.I msmtp
--read-recipients
--read-envelope-from 
.RI [ option\~ .\|.\|.]

.SH QUEUE
Queued messages are stored as \fB.eml\fP files in sub-directories of \fBoutboxd\fP's working directory:

.IP "\fBpending/\fP"
This directory holds newly queued messages. \fBoutboxd\fP will try to send these messages.
.IP "\fBfailed/\fP"
This directory holds messages that failed to send. \fBoutboxd\fP will not try to re-send these messages unless re-queued.

.SH ENVIRONMENT
.IP "SENDMAIL=\fIexecutable\fI"
Configures the executable outboxd uses to send emails. The default is \fImsmtp\fP.
.IP "DBUS_CONNECTION=[\fIsystem\fP | \fIsession\fP]"
Configures the bus connection on which outboxd provides the 
.MR \%garden.tau.Outbox 1
interface. The default is \fIsystem\fP.

.SH AUTHORS
outboxd was written by Tau Gärtli [https://tau.garden]

.SH SEE ALSO
.TP
D-Bus Interface:
.MR garden.tau.Outbox 1
.TP
SMTP Client:
.MR msmtp 1

